server:
  port: 80

spring:
  application:
    name: my-web-api
  datasource:
    name: qms
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driverClassName: com.mysql.jdbc.Driver
       #基本属性
      url: jdbc:mysql://localhost:3306/springbootdb?useSSL=false&characterEncoding=utf8&autoReconnect=true
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 2
  security:
    user:
      name: client
      password: 123456
  mail:
    host: smtp.163.com
    username: cookie_fangfang@163.com
    password: 8qDHpbksrwJaExum
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 25
    defaultEncoding: UTF-8
    protocol: smtp
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.springboot.mybatis.model # 注意：对应实体类的路径

logging:
  level:
    com.springboot.mybatis.dao: trace
